"""Assertive record, affiliation, correction, and reminder use cases."""

from people_context.app._mutation import (
    InvalidCorrectionError,
    InvalidReminderError,
    OrganizationNotFoundError,
    PersonNotFoundError,
    RecordNotFoundError,
    ReminderNotActiveError,
)
from people_context.app.records.affiliations import SetAffiliation, SetAffiliationInput
from people_context.app.records.corrections import CorrectRecord, CorrectRecordInput
from people_context.app.records.doctor import (
    DOCTOR_FORMAT,
    DOCTOR_VERSION,
    FINDING_CODES,
    CliAction,
    DoctorError,
    DoctorFinding,
    DoctorReport,
    FactEvidence,
    FindingCode,
    FindingPerson,
    McpAction,
    NameEvidence,
    ReferenceEvidence,
    ReportDoctorFindings,
    render_doctor_json,
)
from people_context.app.records.facts import RecordFact, RecordFactInput
from people_context.app.records.interactions import RecordInteraction, RecordInteractionInput
from people_context.app.records.observations import RecordObservation, RecordObservationInput
from people_context.app.records.reminders import (
    CompleteReminder,
    CompleteReminderInput,
    ListReminders,
    ListRemindersInput,
    SetReminder,
    SetReminderInput,
)
from people_context.app.records.supersession import (
    FACT_ENTITY_TYPE,
    REASON_AFTER_VALID_TO,
    REASON_NO_PRIOR_DAY,
    REASON_NOT_AFTER_VALID_FROM,
    SUPERSEDE_OP,
    SUPERSEDED_FIELD,
    InvalidSupersessionError,
    SupersedeFact,
    SupersedeFactInput,
    SupersedeFactResult,
)
from people_context.app.records.traits import RecordTrait, RecordTraitInput

__all__ = [
    "DOCTOR_FORMAT",
    "DOCTOR_VERSION",
    "FACT_ENTITY_TYPE",
    "FINDING_CODES",
    "REASON_AFTER_VALID_TO",
    "REASON_NOT_AFTER_VALID_FROM",
    "REASON_NO_PRIOR_DAY",
    "SUPERSEDED_FIELD",
    "SUPERSEDE_OP",
    "CliAction",
    "CompleteReminder",
    "CompleteReminderInput",
    "CorrectRecord",
    "CorrectRecordInput",
    "DoctorError",
    "DoctorFinding",
    "DoctorReport",
    "FactEvidence",
    "FindingCode",
    "FindingPerson",
    "InvalidCorrectionError",
    "InvalidSupersessionError",
    "InvalidReminderError",
    "ListReminders",
    "ListRemindersInput",
    "McpAction",
    "NameEvidence",
    "OrganizationNotFoundError",
    "PersonNotFoundError",
    "RecordFact",
    "RecordFactInput",
    "RecordInteraction",
    "RecordInteractionInput",
    "RecordNotFoundError",
    "RecordObservation",
    "RecordObservationInput",
    "RecordTrait",
    "RecordTraitInput",
    "ReferenceEvidence",
    "ReminderNotActiveError",
    "ReportDoctorFindings",
    "SetAffiliation",
    "SetAffiliationInput",
    "SetReminder",
    "SetReminderInput",
    "SupersedeFact",
    "SupersedeFactInput",
    "SupersedeFactResult",
    "render_doctor_json",
]
