/**
 * Build the distributable plugin tree.
 *
 * Obsidian loads one CommonJS `main.js` beside a `manifest.json`, so the TypeScript sources
 * are bundled rather than emitted file-by-file. The build is deliberately boring: no
 * minification, no source maps, no timestamps, and a pinned esbuild version in the lockfile,
 * so two clean installations of the same commit produce byte-identical artifacts.
 *
 * Output goes to `build/`, which is not committed. Nothing generated here is a source of
 * truth; the release workflow rebuilds it.
 */

import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const root = dirname(fileURLToPath(import.meta.url));
const outputDir = join(root, "build");

/** Everything Obsidian and Electron provide at runtime, which must never be bundled in. */
const external = [
  "obsidian",
  "electron",
  "node:child_process",
  "node:crypto",
  "node:fs",
  "node:os",
  "node:path",
  "node:process",
  "node:util",
];

await rm(outputDir, { recursive: true, force: true });
await mkdir(outputDir, { recursive: true });

await build({
  entryPoints: [join(root, "src/main.ts")],
  outfile: join(outputDir, "main.js"),
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "es2022",
  external,
  // Determinism first: nothing below may vary between two builds of the same input.
  minify: false,
  sourcemap: false,
  treeShaking: true,
  logLevel: "info",
  banner: {
    js: "/* People Context for Obsidian — generated by esbuild. Do not edit. */",
  },
});

for (const asset of ["manifest.json", "styles.css"]) {
  await writeFile(join(outputDir, asset), await readFile(join(root, asset)));
}

// Print a checksum per artifact so a release job can compare two clean builds without
// unpacking anything.
const names = (await readdir(outputDir)).sort();
for (const name of names) {
  const digest = createHash("sha256").update(await readFile(join(outputDir, name))).digest("hex");
  process.stdout.write(`${digest}  ${name}\n`);
}
