"""Read-only reports derived from stored signal, without recording new data."""

from people_context.app.insights.stale import (
    DEFAULT_STALE_LIMIT,
    DEFAULT_THRESHOLD_DAYS,
    MAX_STALE_LIMIT,
    MAX_THRESHOLD_DAYS,
    MIN_STALE_LIMIT,
    MIN_THRESHOLD_DAYS,
    GetStaleRelationships,
    StalePersonResult,
    StaleRelationshipsError,
    StaleRelationshipsResult,
)
from people_context.app.insights.timeline import (
    DEFAULT_TIMELINE_LIMIT,
    MAX_TIMELINE_EVIDENCE_LINKS,
    MAX_TIMELINE_LIMIT,
    MIN_TIMELINE_LIMIT,
    PERSON_TIMELINE_FORMAT,
    PERSON_TIMELINE_VERSION,
    GetPersonTimeline,
    PersonTimelineDocument,
    PersonTimelineError,
    PersonTimelineResult,
    TimelineEntry,
    person_timeline_document,
    render_timeline_json,
)
from people_context.app.insights.upcoming import (
    BIRTHDAY_LABEL,
    BIRTHDAY_PREDICATE,
    DEFAULT_WINDOW_DAYS,
    MAX_WINDOW_DAYS,
    MIN_WINDOW_DAYS,
    ListUpcomingDates,
    UpcomingDateEntry,
    UpcomingDateKind,
    UpcomingDatesError,
    UpcomingDatesResult,
)

__all__ = [
    "BIRTHDAY_LABEL",
    "BIRTHDAY_PREDICATE",
    "DEFAULT_STALE_LIMIT",
    "DEFAULT_TIMELINE_LIMIT",
    "DEFAULT_THRESHOLD_DAYS",
    "DEFAULT_WINDOW_DAYS",
    "MAX_STALE_LIMIT",
    "MAX_TIMELINE_EVIDENCE_LINKS",
    "MAX_TIMELINE_LIMIT",
    "MAX_THRESHOLD_DAYS",
    "MAX_WINDOW_DAYS",
    "MIN_STALE_LIMIT",
    "MIN_TIMELINE_LIMIT",
    "MIN_THRESHOLD_DAYS",
    "MIN_WINDOW_DAYS",
    "PERSON_TIMELINE_FORMAT",
    "PERSON_TIMELINE_VERSION",
    "GetPersonTimeline",
    "GetStaleRelationships",
    "ListUpcomingDates",
    "PersonTimelineDocument",
    "PersonTimelineError",
    "PersonTimelineResult",
    "StalePersonResult",
    "StaleRelationshipsError",
    "StaleRelationshipsResult",
    "TimelineEntry",
    "UpcomingDateEntry",
    "UpcomingDateKind",
    "UpcomingDatesError",
    "UpcomingDatesResult",
    "person_timeline_document",
    "render_timeline_json",
]
